# lightning.pytorch==2.4.0
seed_everything: true
lr: 0.0004
wdecay: 0.0001
trainer:
  # max_epochs: 45
  max_epochs: 420 # 22872 / batch_size(8) = 2859 iterations per epoch, 2859*420=1200780 ~= 1.2M iterations
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  devices: 0,1,2,3,4,5,6,7
model:
  class_path: ptlflow.models.flownets_wb
  init_args:
    div_flow: 20.0
    input_channels: 6
    batch_norm: False
    loss_start_scale: 4
    loss_num_scales: 5
    loss_base_weight: 0.32
    loss_norm: L2
    warm_start: false
data:
  train_dataset: chairs
  val_dataset: sintel-final-val+kitti-2015-val
  train_batch_size: 8
  train_num_workers: 8
  train_crop_size: [368, 496]
  # train_crop_size: [352, 480]
  train_transform_cuda: false
  train_transform_fp16: false
